GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestResetClassUtility.cls
/*
 * Utility class to create data for TestResetClass
 */ 
public class TestResetClassUtility {
    /*
     * Creates a class and related students
     * @param noOfStudents number of students
     */ 
    public static Class__c createClass(Integer noOfStudents){
        
        Class__c cls = new Class__c(name = 'testClass');
        insert cls;
        list<Student__c> students = new list<student__c>();
        for(Integer j = 0;j<noOfStudents;j++){
            students.add(new Student__c(name='student'+j,lastName__c = 'sur'+j,class__c = cls.Id));
        }
        insert Students;
        return cls;
    }
    
}