GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Class__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>CBSE</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Class__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Class__c/fields/MaxSize__c.field-meta.xml
<CustomField>
    <fullName>MaxSize__c</fullName>
    <label>MaxSize</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestAjaxForClassController.cls
@isTest
public class TestAjaxForClassController {

    @testSetup
    static void setUpTestdata() {
    	Class__c testClass = new Class__c(Name = 'testClass');
        insert testClass;
    }
    
    @isTest
    static void testUpdateClass() {
        AjaxForClassController controller = new AjaxForClassController();
        // call getClass method
        list<Class__c> allClasses = controller.getClasses();
        controller.ClassId = allClasses[0].Id;
        //call editClass method
        controller.editClass();
        controller.SelectedClass.Name = 'test1';
        controller.SelectedClass.Board__c = 'RAJ';
        controller.SelectedClass.Fee__c = 10000;
        controller.SelectedClass.MaxSize__c = 40;
        //call updateClassMethod
        controller.updateClass();
        allClasses = controller.getClasses();
        System.assertEquals(10000, allClasses[0].Fee__c,'Class not updated');
    }
    
    @isTest
    static void testDeleteClass() {
        AjaxForClassController controller = new AjaxForClassController();
        list<Class__c> allClasses = controller.getClasses();
        controller.ClassId = allClasses[0].Id;
        controller.deleteClass();
        allClasses = controller.getClasses();
        System.assertEquals(0, allClasses.size(),'Class not deleted');
    }
}