GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestStudentDetailController.cls
@isTest
public class TestStudentDetailController {
    
    @testSetup
    static void setUpTestdata() {
    	Class__c testClass = new Class__c(Name = 'testClass');
        insert testClass;
        Student__c testStudent = new Student__c(lastName__c = 'testStudent', Class__c = testClass.Id);
        insert testStudent;
    }
    
    @isTest
    static void testSavePdf() {
        Student__c testStudent = [SELECT Name , Class__c FROM Student__c WHERE lastName__c = 'testStudent'];
        StudentDetailController stdController = new StudentDetailController(new ApexPages.StandardController(testStudent));
        stdController.savePdf();
        ID currentPdf = [SELECT Id FROM Attachment WHERE parentId = :testStudent.Id ][0].Id;
        stdController.savePdf();
        list<Attachment> attachments = [SELECT Id FROM Attachment WHERE isDeleted = true AND parentId = :testStudent.Id ALL ROWS];
        System.assertEquals(1,[SELECT COUNT() FROM Attachment WHERE ParentId =: testStudent.Id], 'Attachment was not Created as expected');
        System.assertEquals(currentPdf, attachments[attachments.size() - 1].Id,'PDF was not replaced');
    }
}