GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/SearchStudent.cls
public class SearchStudent {
    
    public static list<String> getStudentsFromClass(ID classId){
        
        Student__c[] students = [SELECT Name FROM Student__c WHERE Class__r.ID=:classId]; 
        list<String> listOfNames = new list<String>();
        for(Student__c s : students){
            listOfNames.add(s.name);
        }
        return listOfNames;
    }
    
    public static map<String,Set<String>> getStudentsWithClass(){
        
        list<Class__c> classStudents= [SELECT Name , (SELECT Name FROM Students__r)  FROM Class__c ];
        map<String,Set<String>> mapOfClassStudents = new map<String,Set<String>>();
        for(Class__c c : classStudents){
            Set<String> studentSet = new Set<String>();
            for(Student__c s : c.Students__r){
                studentSet.add(s.name);
            }
            mapOfClassStudents.put(c.Name, studentSet);             
        }
        return mapOfClassStudents;
    }
    
}