GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Class__c/fields/Custom_Status__c.field-meta.xml
<CustomField>
    <fullName>Custom_Status__c</fullName>
    <label>Custom Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Reset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestResetClass.cls
/*
 * Test class for ResetClass class
 */ 
@isTest
public class TestResetClass {
    /*
     * Test Class object when status changes to 'Reset'
     */ 
    @isTest
    static void CheckWhenStatusIsReset(){
        Class__c newClass = TestResetClassUtility.createClass(20);
        Integer count= [SELECT count() FROM Student__c Where Class__r.Id = :newClass.Id];
        System.assertEquals(count,20);
        test.startTest();
        newClass.custom_Status__c = 'Reset';
        Update newClass;
        test.stopTest();
        count= [SELECT count() FROM Student__c Where Class__r.Id = :newClass.Id];
        System.assertEquals(count,0);
        
    }
    /*
     * Test Class object when status changes to 'Open'
     */
    @isTest
    static void CheckWhenStatusIsOpen(){
        Class__c newClass = TestResetClassUtility.createClass(20);
        Integer count= [SELECT count() FROM Student__c Where Class__r.Id = :newClass.Id];
        System.assertEquals(count,20);
        test.startTest();
        newClass.custom_Status__c = 'Open';
        Update newClass;
        test.stopTest();
        count= [SELECT count() FROM Student__c Where Class__r.Id = :newClass.Id];
        System.assertEquals(count,20);
        
    }
}