GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Class__c/fields/MyCount__c.field-meta.xml
<CustomField>
    <fullName>MyCount__c</fullName>
    <label>MyCount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestUpdateMyCountField.cls
/*
 * Test class for UpdateMyCountField class
 */ 
@isTest
public class TestUpdateMyCountField {
    
    /*
     * Test to Insert single student 
     */ 
    @isTest
    static void InsertStudent(){
        list<Student__c> students = TestUpdateMyCountFieldUtility.CreateStudents(1);
        test.startTest();
        database.SaveResult result = database.Insert(students[0],false);
        test.stopTest();
        Decimal count = [SELECT MyCount__c FROM Class__c WHERE ID IN (SELECT Class__c FROM Student__c WHERE Id = :students)][0].MyCount__c;
        System.assert(result.isSuccess());
        System.assertEquals(1, count);
        
    }
    /*
     * Test to Insert Bulk students 
     */ 
    @isTest
    static void InsertBulkStudents(){
        list<Student__c> students = TestUpdateMyCountFieldUtility.CreateStudents(100);
        test.startTest();
        database.SaveResult[] result = database.Insert(students,false);
        test.stopTest();
        Decimal count = [SELECT MyCount__c FROM Class__c WHERE ID IN (SELECT Class__c FROM Student__c WHERE Id IN :students)][0].MyCount__c;
        System.assertEquals(100, count);
    }
}