GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestJSONFormatController.cls
@isTest
public class TestJSONFormatController {

    @testSetup
    static void setUpTestdata() {
    	Class__c testClass = new Class__c(Name = 'testClass');
        insert testClass;
        Student__c testStudent = new Student__c(lastName__c = 'testStudent', Class__c = testClass.Id);
        insert testStudent;
    }
    
    @isTest
    static void testJSONString() {
        Student__c testStudent = [SELECT Name , Class__c FROM Student__c WHERE lastName__c = 'testStudent'];
        JSONFormatController JSONController = new JSONFormatController(new ApexPages.StandardController(testStudent));
        JSONController.serailize();
        Student__c std = (Student__c)JSON.deserialize(JSONController.JSONObjectString, Student__c.Class);
        System.assert(JSONController.JSONObjectString!=null, 'JSON String not built');
        System.assertEquals(std.Name,testStudent.Name, 'JSON String not built for given object');
    }
}