GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/RemoteDeleteStudentControllerTest.cls
@isTest
public class RemoteDeleteStudentControllerTest {
    
    @testSetup
    public static void testDataSetup() {
        Class__c newClass = new Class__c(name = 'test');
        insert newClass;
        List<Student__c> students = new List<Student__c>();
        for(Integer i = 0 ; i < 100 ; i++) {
            students.add(new Student__c(firstName__c = 'first'+i ,lastName__c = 'last'+i ,Class__c = newClass.Id));
        }
        insert students;
    }
    
    @isTest
    public static void testDelete() {
        List<Student__c> students = [Select Id , firstName__c FROM Student__c];
        List<Id> studentIds = new List<Id>();
        for(Integer index = 0 ; index < students.size() ; index++) {
            studentIds.add(students[index].Id);
        }
        database.DeleteResult[] result = RemoteDeleteStudentController.deleteStudents(studentIds);
        for(Integer i = 0 ; i < result.size() ; i++) {
            System.assertEquals(result[i].isSuccess(), true,'Could not delete all or some records');
        }
        RemoteDeleteStudentController controller = new RemoteDeleteStudentController(new ApexPages.StandardSetController(students));
        System.assertEquals(controller.Render, false,'Could not render page content properly');
    }
}