GET_Training_SFDC/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/objects/Student__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GET_Training_SFDC/force-app/main/default/classes/TestClassHavingFemaleUtility.cls
/*
 * Utility class to create data for TestClassHavingFemale
 */
public class TestClassHavingFemaleUtility {
    
    /*
     * Create a class along with students
     * @param noOfClass number of classes to be created
     * @param noOfGirls number of girls in each class
     */ 
    public static list<Class__c> CreateClass(Integer noOfClass, Integer noOfGirls){
        
        List<Class__c> classes = new List<Class__c>();
        list<Student__c> students = new list<student__c>();
        for(Integer i = 0 ; i<noOfClass;i++){
            class__c newClass = new Class__c(name='test'+i);
            classes.add(newClass);
        }
        insert classes;
        for(Integer j = 0;j<noOfClass;j++){
            class__c cls= classes[j];
            Integer girls=0;
            for(Integer k = 0; k<20;k++){
                if(girls<noOfGirls){
                    students.add(new Student__c(name='student'+j+k,lastName__c='sur'+j+k,sex__c='Female',class__c=cls.Id));
                    girls++;
                }else{
                    students.add(new Student__c(name='student'+j+k,lastName__c='sur'+j+k,sex__c='Male',class__c=cls.Id));
                }
            }
        }
        insert students;
        return classes;
    }
    
}